### ISSUE TITLE
UI freezes after grid maximum

### ISSUE THREAD

**Issue by BasNottrot** [lingtjien/Grid-Tiling-Kwin#47]
I am using Ubuntu 19.04 with KDE Plasma and my UI freezes after opening an application when the grid is full. Mouse is still working, but everything else is frozen, causing me to reboot.

Steps to reproduce:
1. Open Kwin Grid Tiling settings
2. Set rows to 2
3. Set columns to 2
4. Relog
5. Open 4 Konsole's
6. Open a 5th one
7. Freeze

Expected behaviour:
The 5th application either open as a floating window so the grid will stay the same or the grid expands and 5th application opens in the grid.

Workaround:
Increase the rows and columns to a size where I am sure I won't reach the maximum.

**Comment by lingtjien** [comment]
It seems to only happen when you use exactly 1 virtual desktop interesting... Do you use 1 virtual desktop?

I'll get to it :)

**Comment by BasNottrot** [comment]
Yes, I use only 1 desktop :)

**Comment by lingtjien** [comment]
Give the dev branch a try

**Comment by BasNottrot** [comment]
I switched to develop branch and tried again, still freezes unfortunately. Did I have to do anything else apart from switching branches?

**Comment by lingtjien** [comment]
maybe a stupid question but... you did pull the latest changes, right? line `552` in `contents/code/main.js` should read `if (++i >= Converter.size()) {i = 0;}`

**Comment by BasNottrot** [comment]
You made me doubt there for a second, but yes, I pulled the changes and that line is present on 552 ;P

**Comment by lingtjien** [comment]
just making sure :)

did you only pull and change to dev branch or also a reboot? (The script is only loaded at startup by KWin)

**Comment by BasNottrot** [comment]
I also rebooted, but the issue still persists.

**Comment by lingtjien** [comment]
Hmm interesting, if `./local/share/kwin/scripts/grid-tiling/contents/code/main.js` contains the correct code (on `552`) and you rebooted then you should have the right code so I guess that means there's a bug somewhere else that I haven't been able to reproduce...

What settings are you using for the script and could you try with the default settings?

### If I execute these steps now:

1. set default settings and amount of virtual desktops to 1
2. reboot
3. start 4 konsole windows
4. start 5th konsole

### result

 it doesn't freeze anymore but floats the 5th window as expected

### If these steps still give you the freeze then could you try this for me:

1.  open `krunner` type `wm console` and `Open KWin interactive console`
2. click `open` and find the `main.js` file and open it in this console
3. insert these lines:
  - `542` under `var i = start;` add this line `var counter = 0;`
  - `552` under `if (++i >= Converter.Size()) {i = 0;}` add this line `if (counter > 100) {print('should not get here'); return -1;}`
4. click `Plasma` and then click `KWin` and then click `Execute`
5. open 4 instances of konsole
6. open the 5th instance of konsole

**Comment by BasNottrot** [comment]
You talk about setting the amount of desktops, but I can't figure out where in the settings I can specify this? Maybe that causes my issue, because I only have 1 screen?

**Comment by lingtjien** [comment]
`virtual desktops` allow you to have multiple desktops even though you only have 1 physical screen. KWin provides a bunch of global shortcuts to switch between these virtual desktops which you can find in the global shortcuts section `KWin` there is a global shortcut in there called `Show Desktop Grid` which will show you all your virtual desktops at once.

Nevertheless, the script should not freeze regardless of how many virtual desktops you have and I could only reproduce your case when I had a single virtual desktop, so that I fixed and tested on my system and worked...

If the problem still persists I'll have to reproduce your issue first and in order to single out the problem, I'd like us to have the same configuration file to eliminate this as a variable. So there is a small button in the left bottom corner of the UI of this script which resets the configuration to default values, click that and then `ok` then a reboot and see if the problem persists.

**Comment by BasNottrot** [comment]
1. I tried with default settings and 1 desktop, my screen still freezes.

2. I tried with Kwin Console several times,
- The first time I got an notification that KWin had crashed
- The other times my screen freezes, even with the konsole

3. I tried with 2 virtual desktops, when I started adding konsole's from the first (I guess main) desktop, after 4 tiles it switches to the 2nd desktop and starts adding tiles there. Then when the second screen is full, it open the new tiles on top in the second screen. So this works as expected.

3. I tried with 2 virtual desktops, when I started adding konsole's from the second (I guess not the main) desktop, after 4 tiles it switches to the 1st desktop and starts adding tiles there. Then when this sreen is full and I try to open a new one, my laptop freezes again. So the issue only happens on the main screen.

**Comment by lingtjien** [comment]
> I tried with Kwin Console and I got an notification that KWin had crashed, details:
Executable: kwin_x11 PID: 1.851 Signal: Segmentation fault (11) Time: 23-10-2019 11:08:21

I've never been able to crash KWin using the scripting interface...

**Comment by BasNottrot** [comment]
Seems like an issue with KWin, maybe it has something to do with my NVidia GPU, that thing always causes issues with Linux

**Comment by lingtjien** [comment]
I also did notice a few weird bugs lately since one of the latest updates, that sometimes KWin resets itself or something and reloads the entire script... that never caused a crash though

I also just tried your 4th case and it works fine for me...

**Comment by BasNottrot** [comment]
I am currently filing an bug report with KWin

**Comment by lingtjien** [comment]
maybe you could try with an integrated graphics processor, see if that works?

**Comment by BasNottrot** [comment]
I am not sure what an integrated graphics processor is?

**Comment by lingtjien** [comment]
oh some CPU have an integrated graphics unit, like most intel processors (intel UHD630 for example) I believe or the AMD G series such as Ryzen 3200G or 3400G

**Comment by BasNottrot** [comment]
I will close the issue, because it is not related to the script, thanks for the help :)
